ingress:
  enabled: true
  domain: anieto.dev
  subdomain: vidaviajera
  oauth2Enabled: false
  extraAnnotations:
    nginx.ingress.kubernetes.io/app-root: /login.html

deployment:
  image: registry.anieto.dev/v2/adrian/vida-viajera-web
  imagePullSecrets:
  - regcred
  containerPort: 80